name: mowerapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.0
  firebase_database: 10.4.0
  provider: ^6.1.2
  google_maps_flutter: ^2.5.3
  flutter_custom_cards: ^0.2.1
  animated_fab_button_menu: ^0.0.2
  http: ^1.1.0
  quickalert: ^1.1.0
  auto_size_text: ^3.0.0
  location: ^5.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
